#!/usr/bin/env bash
# This script displays "Best School" 10 times, "Hi" after 9th

counter=1
while [ $counter -le 10 ]
do
	echo "Best School"
	if [ $counter = 9 ]
	then
	    echo "Hi"
	fi
	((counter++))
done
