#!/usr/bin/env bash
# Create a RSA key pair
# Name of private key must be school
# Number of bits in created key should be 3072
# Key must be protected by a passphrase
ssh-keygen -b 3072 -f school -t rsa -P betty
